# MissionChange Types
CREATE_MISSION = "CREATE_MISSION"
DELETE_MISSION = "DELETE_MISSION"
ADD_CONTENT = "ADD_CONTENT"
REMOVE_CONTENT = "REMOVE_CONTENT"
CREATE_DATA_FEED = "CREATE_DATA_FEED"
DELETE_DATA_FEED = "DELETE_DATA_FEED"
