class MissionChangeConstants:
    CREATE_MISSION = "CREATE_MISSION"
    DELETE_MISSION = "DELETE_MISSION"
    ADD_CONTENT = "ADD_CONTENT"
    REMOVE_CONTENT = "REMOVE_CONTENT"
    CREATE_DATA_FEED = "CREATE_DATA_FEED"
    DELETE_DATA_FEED = "DELETE_DATA_FEED"


class MissionRoleConstants:
    MISSION_MANAGE_FEEDS = "MISSION_MANAGE_FEEDS"
    MISSION_SET_PASSWORD = "MISSION_SET_PASSWORD"
    MISSION_WRITE = "MISSION_WRITE"
    MISSION_MANAGE_LAYERS = "MISSION_MANAGE_LAYERS"
    MISSION_UPDATE_GROUPS = "MISSION_UPDATE_GROUPS"
    MISSION_DELETE = "MISSION_DELETE"
    MISSION_SET_ROLE = "MISSION_SET_ROLE"
    MISSION_READ = "MISSION_READ"
    MISSION_OWNER = "MISSION_OWNER"
    MISSION_SUBSCRIBER = "MISSION_SUBSCRIBER"
    MISSION_READ_ONLY = "MISSION_READ_ONLY"

    OWNER_ROLE = {'type': MISSION_OWNER, 'permissions': []}
    OWNER_ROLE['permissions'].append(MISSION_MANAGE_FEEDS)
    OWNER_ROLE['permissions'].append(MISSION_SET_PASSWORD)
    OWNER_ROLE['permissions'].append(MISSION_WRITE)
    OWNER_ROLE['permissions'].append(MISSION_MANAGE_LAYERS)
    OWNER_ROLE['permissions'].append(MISSION_UPDATE_GROUPS)
    OWNER_ROLE['permissions'].append(MISSION_DELETE)
    OWNER_ROLE['permissions'].append(MISSION_SET_ROLE)
    OWNER_ROLE['permissions'].append(MISSION_READ)

    SUBSCRIBER_ROLE = {'type': MISSION_SUBSCRIBER, 'permissions': []}
    SUBSCRIBER_ROLE['permissions'].append(MISSION_READ)
    SUBSCRIBER_ROLE['permissions'].append(MISSION_WRITE)

    READ_ONLY_ROLE = {'type': MISSION_READ_ONLY, 'permissions': []}
    READ_ONLY_ROLE['permissions'].append(MISSION_READ)
