"""
These values will be automatically generated by the installer script. If you would like to change
them manually, rename this file secret_key.py
"""
import secrets
import random
import string
import pyotp

secret_key = secrets.token_hex()
node_id = ''.join(random.choices(string.ascii_lowercase + string.digits, k=64))
security_password_salt = secrets.SystemRandom().getrandbits(128)
mediamtx_token = secrets.SystemRandom().getrandbits(128)
totp_secrets = {1: pyotp.random_base32()}
server_address = "example.com"
mail_username = 'me@example.com'  # Only required if you enable email
mail_password = 'changeme'  # Only required if you enable email
