# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: opentakserver/proto/cotevent.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'opentakserver/proto/cotevent.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from opentakserver.proto import detail_pb2 as opentakserver_dot_proto_dot_detail__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"opentakserver/proto/cotevent.proto\x12\x1f\x61takmap.commoncommo.protobuf.v1\x1a opentakserver/proto/detail.proto\"\xb4\x02\n\x08\x43otEvent\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0e\n\x06\x61\x63\x63\x65ss\x18\x02 \x01(\t\x12\x0b\n\x03qos\x18\x03 \x01(\t\x12\x0c\n\x04opex\x18\x04 \x01(\t\x12\x0e\n\x06\x63\x61veat\x18\x10 \x01(\t\x12\x15\n\rreleaseableTo\x18\x11 \x01(\t\x12\x0b\n\x03uid\x18\x05 \x01(\t\x12\x10\n\x08sendTime\x18\x06 \x01(\x04\x12\x11\n\tstartTime\x18\x07 \x01(\x04\x12\x11\n\tstaleTime\x18\x08 \x01(\x04\x12\x0b\n\x03how\x18\t \x01(\t\x12\x0b\n\x03lat\x18\n \x01(\x01\x12\x0b\n\x03lon\x18\x0b \x01(\x01\x12\x0b\n\x03hae\x18\x0c \x01(\x01\x12\n\n\x02\x63\x65\x18\r \x01(\x01\x12\n\n\x02le\x18\x0e \x01(\x01\x12\x37\n\x06\x64\x65tail\x18\x0f \x01(\x0b\x32\'.atakmap.commoncommo.protobuf.v1.Detailb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'opentakserver.proto.cotevent_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_COTEVENT']._serialized_start=106
  _globals['_COTEVENT']._serialized_end=414
# @@protoc_insertion_point(module_scope)
