# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: opentakserver/proto/detail.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'opentakserver/proto/detail.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from opentakserver.proto import contact_pb2 as opentakserver_dot_proto_dot_contact__pb2
from opentakserver.proto import group_pb2 as opentakserver_dot_proto_dot_group__pb2
from opentakserver.proto import precisionlocation_pb2 as opentakserver_dot_proto_dot_precisionlocation__pb2
from opentakserver.proto import status_pb2 as opentakserver_dot_proto_dot_status__pb2
from opentakserver.proto import takv_pb2 as opentakserver_dot_proto_dot_takv__pb2
from opentakserver.proto import track_pb2 as opentakserver_dot_proto_dot_track__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n opentakserver/proto/detail.proto\x12\x1f\x61takmap.commoncommo.protobuf.v1\x1a!opentakserver/proto/contact.proto\x1a\x1fopentakserver/proto/group.proto\x1a+opentakserver/proto/precisionlocation.proto\x1a opentakserver/proto/status.proto\x1a\x1eopentakserver/proto/takv.proto\x1a\x1fopentakserver/proto/track.proto\"\x81\x03\n\x06\x44\x65tail\x12\x11\n\txmlDetail\x18\x01 \x01(\t\x12\x39\n\x07\x63ontact\x18\x02 \x01(\x0b\x32(.atakmap.commoncommo.protobuf.v1.Contact\x12\x35\n\x05group\x18\x03 \x01(\x0b\x32&.atakmap.commoncommo.protobuf.v1.Group\x12M\n\x11precisionLocation\x18\x04 \x01(\x0b\x32\x32.atakmap.commoncommo.protobuf.v1.PrecisionLocation\x12\x37\n\x06status\x18\x05 \x01(\x0b\x32\'.atakmap.commoncommo.protobuf.v1.Status\x12\x33\n\x04takv\x18\x06 \x01(\x0b\x32%.atakmap.commoncommo.protobuf.v1.Takv\x12\x35\n\x05track\x18\x07 \x01(\x0b\x32&.atakmap.commoncommo.protobuf.v1.Trackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'opentakserver.proto.detail_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DETAIL']._serialized_start=282
  _globals['_DETAIL']._serialized_end=667
# @@protoc_insertion_point(module_scope)
