# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from opentakserver.proto import fig_pb2 as opentakserver_dot_proto_dot_fig__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in opentakserver/proto/fig_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FederatedChannelStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendOneEvent = channel.unary_unary(
                '/com.atakmap.FederatedChannel/SendOneEvent',
                request_serializer=opentakserver_dot_proto_dot_fig__pb2.FederatedEvent.SerializeToString,
                response_deserializer=opentakserver_dot_proto_dot_fig__pb2.Empty.FromString,
                _registered_method=True)
        self.BinaryMessageStream = channel.stream_unary(
                '/com.atakmap.FederatedChannel/BinaryMessageStream',
                request_serializer=opentakserver_dot_proto_dot_fig__pb2.BinaryBlob.SerializeToString,
                response_deserializer=opentakserver_dot_proto_dot_fig__pb2.Empty.FromString,
                _registered_method=True)
        self.SendOneBlob = channel.unary_unary(
                '/com.atakmap.FederatedChannel/SendOneBlob',
                request_serializer=opentakserver_dot_proto_dot_fig__pb2.BinaryBlob.SerializeToString,
                response_deserializer=opentakserver_dot_proto_dot_fig__pb2.Empty.FromString,
                _registered_method=True)
        self.getIdentity = channel.unary_unary(
                '/com.atakmap.FederatedChannel/getIdentity',
                request_serializer=opentakserver_dot_proto_dot_fig__pb2.Empty.SerializeToString,
                response_deserializer=opentakserver_dot_proto_dot_fig__pb2.Identity.FromString,
                _registered_method=True)
        self.ClientEventStream = channel.unary_stream(
                '/com.atakmap.FederatedChannel/ClientEventStream',
                request_serializer=opentakserver_dot_proto_dot_fig__pb2.Subscription.SerializeToString,
                response_deserializer=opentakserver_dot_proto_dot_fig__pb2.FederatedEvent.FromString,
                _registered_method=True)
        self.ServerEventStream = channel.stream_unary(
                '/com.atakmap.FederatedChannel/ServerEventStream',
                request_serializer=opentakserver_dot_proto_dot_fig__pb2.FederatedEvent.SerializeToString,
                response_deserializer=opentakserver_dot_proto_dot_fig__pb2.Subscription.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/com.atakmap.FederatedChannel/HealthCheck',
                request_serializer=opentakserver_dot_proto_dot_fig__pb2.ClientHealth.SerializeToString,
                response_deserializer=opentakserver_dot_proto_dot_fig__pb2.ServerHealth.FromString,
                _registered_method=True)
        self.ClientROLStream = channel.unary_stream(
                '/com.atakmap.FederatedChannel/ClientROLStream',
                request_serializer=opentakserver_dot_proto_dot_fig__pb2.Subscription.SerializeToString,
                response_deserializer=opentakserver_dot_proto_dot_fig__pb2.ROL.FromString,
                _registered_method=True)
        self.ServerROLStream = channel.stream_unary(
                '/com.atakmap.FederatedChannel/ServerROLStream',
                request_serializer=opentakserver_dot_proto_dot_fig__pb2.ROL.SerializeToString,
                response_deserializer=opentakserver_dot_proto_dot_fig__pb2.Subscription.FromString,
                _registered_method=True)
        self.ServerFederateGroupsStream = channel.unary_stream(
                '/com.atakmap.FederatedChannel/ServerFederateGroupsStream',
                request_serializer=opentakserver_dot_proto_dot_fig__pb2.Subscription.SerializeToString,
                response_deserializer=opentakserver_dot_proto_dot_fig__pb2.FederateGroups.FromString,
                _registered_method=True)
        self.ClientFederateGroupsStream = channel.stream_unary(
                '/com.atakmap.FederatedChannel/ClientFederateGroupsStream',
                request_serializer=opentakserver_dot_proto_dot_fig__pb2.FederateGroups.SerializeToString,
                response_deserializer=opentakserver_dot_proto_dot_fig__pb2.Subscription.FromString,
                _registered_method=True)


class FederatedChannelServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendOneEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BinaryMessageStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendOneBlob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getIdentity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClientEventStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ServerEventStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClientROLStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ServerROLStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ServerFederateGroupsStream(self, request, context):
        """client federate requests the Federate Server's groups, serverStreamingCall
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClientFederateGroupsStream(self, request_iterator, context):
        """the client federate sends its groups to the Federate Server, clientStreamingCall
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FederatedChannelServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendOneEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.SendOneEvent,
                    request_deserializer=opentakserver_dot_proto_dot_fig__pb2.FederatedEvent.FromString,
                    response_serializer=opentakserver_dot_proto_dot_fig__pb2.Empty.SerializeToString,
            ),
            'BinaryMessageStream': grpc.stream_unary_rpc_method_handler(
                    servicer.BinaryMessageStream,
                    request_deserializer=opentakserver_dot_proto_dot_fig__pb2.BinaryBlob.FromString,
                    response_serializer=opentakserver_dot_proto_dot_fig__pb2.Empty.SerializeToString,
            ),
            'SendOneBlob': grpc.unary_unary_rpc_method_handler(
                    servicer.SendOneBlob,
                    request_deserializer=opentakserver_dot_proto_dot_fig__pb2.BinaryBlob.FromString,
                    response_serializer=opentakserver_dot_proto_dot_fig__pb2.Empty.SerializeToString,
            ),
            'getIdentity': grpc.unary_unary_rpc_method_handler(
                    servicer.getIdentity,
                    request_deserializer=opentakserver_dot_proto_dot_fig__pb2.Empty.FromString,
                    response_serializer=opentakserver_dot_proto_dot_fig__pb2.Identity.SerializeToString,
            ),
            'ClientEventStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ClientEventStream,
                    request_deserializer=opentakserver_dot_proto_dot_fig__pb2.Subscription.FromString,
                    response_serializer=opentakserver_dot_proto_dot_fig__pb2.FederatedEvent.SerializeToString,
            ),
            'ServerEventStream': grpc.stream_unary_rpc_method_handler(
                    servicer.ServerEventStream,
                    request_deserializer=opentakserver_dot_proto_dot_fig__pb2.FederatedEvent.FromString,
                    response_serializer=opentakserver_dot_proto_dot_fig__pb2.Subscription.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=opentakserver_dot_proto_dot_fig__pb2.ClientHealth.FromString,
                    response_serializer=opentakserver_dot_proto_dot_fig__pb2.ServerHealth.SerializeToString,
            ),
            'ClientROLStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ClientROLStream,
                    request_deserializer=opentakserver_dot_proto_dot_fig__pb2.Subscription.FromString,
                    response_serializer=opentakserver_dot_proto_dot_fig__pb2.ROL.SerializeToString,
            ),
            'ServerROLStream': grpc.stream_unary_rpc_method_handler(
                    servicer.ServerROLStream,
                    request_deserializer=opentakserver_dot_proto_dot_fig__pb2.ROL.FromString,
                    response_serializer=opentakserver_dot_proto_dot_fig__pb2.Subscription.SerializeToString,
            ),
            'ServerFederateGroupsStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ServerFederateGroupsStream,
                    request_deserializer=opentakserver_dot_proto_dot_fig__pb2.Subscription.FromString,
                    response_serializer=opentakserver_dot_proto_dot_fig__pb2.FederateGroups.SerializeToString,
            ),
            'ClientFederateGroupsStream': grpc.stream_unary_rpc_method_handler(
                    servicer.ClientFederateGroupsStream,
                    request_deserializer=opentakserver_dot_proto_dot_fig__pb2.FederateGroups.FromString,
                    response_serializer=opentakserver_dot_proto_dot_fig__pb2.Subscription.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.atakmap.FederatedChannel', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('com.atakmap.FederatedChannel', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FederatedChannel(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendOneEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.atakmap.FederatedChannel/SendOneEvent',
            opentakserver_dot_proto_dot_fig__pb2.FederatedEvent.SerializeToString,
            opentakserver_dot_proto_dot_fig__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BinaryMessageStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/com.atakmap.FederatedChannel/BinaryMessageStream',
            opentakserver_dot_proto_dot_fig__pb2.BinaryBlob.SerializeToString,
            opentakserver_dot_proto_dot_fig__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendOneBlob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.atakmap.FederatedChannel/SendOneBlob',
            opentakserver_dot_proto_dot_fig__pb2.BinaryBlob.SerializeToString,
            opentakserver_dot_proto_dot_fig__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getIdentity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.atakmap.FederatedChannel/getIdentity',
            opentakserver_dot_proto_dot_fig__pb2.Empty.SerializeToString,
            opentakserver_dot_proto_dot_fig__pb2.Identity.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClientEventStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/com.atakmap.FederatedChannel/ClientEventStream',
            opentakserver_dot_proto_dot_fig__pb2.Subscription.SerializeToString,
            opentakserver_dot_proto_dot_fig__pb2.FederatedEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ServerEventStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/com.atakmap.FederatedChannel/ServerEventStream',
            opentakserver_dot_proto_dot_fig__pb2.FederatedEvent.SerializeToString,
            opentakserver_dot_proto_dot_fig__pb2.Subscription.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.atakmap.FederatedChannel/HealthCheck',
            opentakserver_dot_proto_dot_fig__pb2.ClientHealth.SerializeToString,
            opentakserver_dot_proto_dot_fig__pb2.ServerHealth.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClientROLStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/com.atakmap.FederatedChannel/ClientROLStream',
            opentakserver_dot_proto_dot_fig__pb2.Subscription.SerializeToString,
            opentakserver_dot_proto_dot_fig__pb2.ROL.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ServerROLStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/com.atakmap.FederatedChannel/ServerROLStream',
            opentakserver_dot_proto_dot_fig__pb2.ROL.SerializeToString,
            opentakserver_dot_proto_dot_fig__pb2.Subscription.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ServerFederateGroupsStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/com.atakmap.FederatedChannel/ServerFederateGroupsStream',
            opentakserver_dot_proto_dot_fig__pb2.Subscription.SerializeToString,
            opentakserver_dot_proto_dot_fig__pb2.FederateGroups.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClientFederateGroupsStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/com.atakmap.FederatedChannel/ClientFederateGroupsStream',
            opentakserver_dot_proto_dot_fig__pb2.FederateGroups.SerializeToString,
            opentakserver_dot_proto_dot_fig__pb2.Subscription.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
