# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: opentakserver/proto/message.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'opentakserver/proto/message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from opentakserver.proto import takmessage_pb2 as opentakserver_dot_proto_dot_takmessage__pb2
from opentakserver.proto import binarypayload_pb2 as opentakserver_dot_proto_dot_binarypayload__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!opentakserver/proto/message.proto\x12\x1f\x61takmap.commoncommo.protobuf.v1\x1a$opentakserver/proto/takmessage.proto\x1a\'opentakserver/proto/binarypayload.proto\"\xaa\x02\n\x07Message\x12<\n\x07payload\x18\x01 \x01(\x0b\x32+.atakmap.commoncommo.protobuf.v1.TakMessage\x12\x0e\n\x06source\x18\x02 \x01(\t\x12\x10\n\x08\x63lientId\x18\x03 \x01(\t\x12\x0e\n\x06groups\x18\x04 \x03(\t\x12\x16\n\x0e\x64\x65stClientUids\x18\x05 \x03(\t\x12\x15\n\rdestCallsigns\x18\x06 \x03(\t\x12\x12\n\nprovenance\x18\x07 \x03(\t\x12\x0f\n\x07\x61rchive\x18\x08 \x01(\x08\x12\x10\n\x08\x66\x65\x65\x64Uuid\x18\t \x01(\t\x12\x14\n\x0c\x63onnectionId\x18\n \x01(\t\x12\x33\n\x06\x62loads\x18\x0b \x03(\x0b\x32#.gov.tak.cop.proto.v1.BinaryPayloadb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'opentakserver.proto.message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGE']._serialized_start=150
  _globals['_MESSAGE']._serialized_end=448
# @@protoc_insertion_point(module_scope)
