# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: opentakserver/proto/missionannouncement.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'opentakserver/proto/missionannouncement.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from opentakserver.proto import takmessage_pb2 as opentakserver_dot_proto_dot_takmessage__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-opentakserver/proto/missionannouncement.proto\x12\x1f\x61takmap.commoncommo.protobuf.v1\x1a$opentakserver/proto/takmessage.proto\"\xe8\x01\n\x13MissionAnnouncement\x12<\n\x07payload\x18\x01 \x01(\x0b\x32+.atakmap.commoncommo.protobuf.v1.TakMessage\x12\x13\n\x0bmissionName\x18\x02 \x01(\t\x12\x1f\n\x17missionAnnouncementType\x18\x03 \x01(\t\x12\x12\n\ncreatorUid\x18\x04 \x01(\t\x12\x13\n\x0bgroupVector\x18\x05 \x01(\t\x12\x11\n\tclientUid\x18\x06 \x01(\t\x12\x0c\n\x04uids\x18\x07 \x03(\t\x12\x13\n\x0bmissionGuid\x18\x08 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'opentakserver.proto.missionannouncement_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MISSIONANNOUNCEMENT']._serialized_start=121
  _globals['_MISSIONANNOUNCEMENT']._serialized_end=353
# @@protoc_insertion_point(module_scope)
