# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from opentakserver.proto import streaminginput_pb2 as opentakserver_dot_proto_dot_streaminginput__pb2
from opentakserver.proto import takmessage_pb2 as opentakserver_dot_proto_dot_takmessage__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in opentakserver/proto/streaminginput_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InputChannelStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ClientTakMessageStream = channel.unary_stream(
                '/com.atakmap.InputChannel/ClientTakMessageStream',
                request_serializer=opentakserver_dot_proto_dot_streaminginput__pb2.ClientSubscription.SerializeToString,
                response_deserializer=opentakserver_dot_proto_dot_takmessage__pb2.TakMessage.FromString,
                _registered_method=True)
        self.ServerTakMessageStream = channel.stream_unary(
                '/com.atakmap.InputChannel/ServerTakMessageStream',
                request_serializer=opentakserver_dot_proto_dot_takmessage__pb2.TakMessage.SerializeToString,
                response_deserializer=opentakserver_dot_proto_dot_streaminginput__pb2.ClientSubscription.FromString,
                _registered_method=True)
        self.VersionCheck = channel.unary_unary(
                '/com.atakmap.InputChannel/VersionCheck',
                request_serializer=opentakserver_dot_proto_dot_streaminginput__pb2.ClientVersion.SerializeToString,
                response_deserializer=opentakserver_dot_proto_dot_streaminginput__pb2.ServerVersion.FromString,
                _registered_method=True)


class InputChannelServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ClientTakMessageStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ServerTakMessageStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VersionCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InputChannelServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ClientTakMessageStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ClientTakMessageStream,
                    request_deserializer=opentakserver_dot_proto_dot_streaminginput__pb2.ClientSubscription.FromString,
                    response_serializer=opentakserver_dot_proto_dot_takmessage__pb2.TakMessage.SerializeToString,
            ),
            'ServerTakMessageStream': grpc.stream_unary_rpc_method_handler(
                    servicer.ServerTakMessageStream,
                    request_deserializer=opentakserver_dot_proto_dot_takmessage__pb2.TakMessage.FromString,
                    response_serializer=opentakserver_dot_proto_dot_streaminginput__pb2.ClientSubscription.SerializeToString,
            ),
            'VersionCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.VersionCheck,
                    request_deserializer=opentakserver_dot_proto_dot_streaminginput__pb2.ClientVersion.FromString,
                    response_serializer=opentakserver_dot_proto_dot_streaminginput__pb2.ServerVersion.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.atakmap.InputChannel', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('com.atakmap.InputChannel', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InputChannel(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ClientTakMessageStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/com.atakmap.InputChannel/ClientTakMessageStream',
            opentakserver_dot_proto_dot_streaminginput__pb2.ClientSubscription.SerializeToString,
            opentakserver_dot_proto_dot_takmessage__pb2.TakMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ServerTakMessageStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/com.atakmap.InputChannel/ServerTakMessageStream',
            opentakserver_dot_proto_dot_takmessage__pb2.TakMessage.SerializeToString,
            opentakserver_dot_proto_dot_streaminginput__pb2.ClientSubscription.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VersionCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.atakmap.InputChannel/VersionCheck',
            opentakserver_dot_proto_dot_streaminginput__pb2.ClientVersion.SerializeToString,
            opentakserver_dot_proto_dot_streaminginput__pb2.ServerVersion.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
