# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: opentakserver/proto/streaminginput.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'opentakserver/proto/streaminginput.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from opentakserver.proto import takmessage_pb2 as opentakserver_dot_proto_dot_takmessage__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n(opentakserver/proto/streaminginput.proto\x12\x0b\x63om.atakmap\x1a$opentakserver/proto/takmessage.proto\"A\n\x12\x43lientSubscription\x12+\n\x07version\x18\x01 \x01(\x0b\x32\x1a.com.atakmap.ClientVersion\" \n\rClientVersion\x12\x0f\n\x07version\x18\x01 \x01(\x05\"4\n\rServerVersion\x12\x0f\n\x07version\x18\x01 \x01(\x05\x12\x12\n\ncompatible\x18\x02 \x01(\x08\x32\xb0\x02\n\x0cInputChannel\x12j\n\x16\x43lientTakMessageStream\x12\x1f.com.atakmap.ClientSubscription\x1a+.atakmap.commoncommo.protobuf.v1.TakMessage\"\x00\x30\x01\x12j\n\x16ServerTakMessageStream\x12+.atakmap.commoncommo.protobuf.v1.TakMessage\x1a\x1f.com.atakmap.ClientSubscription\"\x00(\x01\x12H\n\x0cVersionCheck\x12\x1a.com.atakmap.ClientVersion\x1a\x1a.com.atakmap.ServerVersion\"\x00\x42.\n\x0f\x63om.atakmap.TakB\x13StreamingInputProtoP\x01\xa2\x02\x03TAKb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'opentakserver.proto.streaminginput_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\017com.atakmap.TakB\023StreamingInputProtoP\001\242\002\003TAK'
  _globals['_CLIENTSUBSCRIPTION']._serialized_start=95
  _globals['_CLIENTSUBSCRIPTION']._serialized_end=160
  _globals['_CLIENTVERSION']._serialized_start=162
  _globals['_CLIENTVERSION']._serialized_end=194
  _globals['_SERVERVERSION']._serialized_start=196
  _globals['_SERVERVERSION']._serialized_end=248
  _globals['_INPUTCHANNEL']._serialized_start=251
  _globals['_INPUTCHANNEL']._serialized_end=555
# @@protoc_insertion_point(module_scope)
