# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from opentakserver.federation.proto import fig_pb2 as fig__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in fig_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FederatedChannelStub(object):
    """Federation v2 transport. v1 exchanges FederatedEvent as length-prefixed
    frames over a raw TLS socket and ignores this service; v2 uses these RPCs
    over gRPC/HTTP2. OpenTAKServer implements the situational-awareness subset:
    getIdentity, HealthCheck, and the ClientEventStream/ServerEventStream event
    streams. The ROL (mission federation) and group-mapping RPCs are declared
    for wire compatibility but not served.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendOneEvent = channel.unary_unary(
                '/com.atakmap.FederatedChannel/SendOneEvent',
                request_serializer=fig__pb2.FederatedEvent.SerializeToString,
                response_deserializer=fig__pb2.Empty.FromString,
                _registered_method=True)
        self.BinaryMessageStream = channel.stream_unary(
                '/com.atakmap.FederatedChannel/BinaryMessageStream',
                request_serializer=fig__pb2.BinaryBlob.SerializeToString,
                response_deserializer=fig__pb2.Empty.FromString,
                _registered_method=True)
        self.SendOneBlob = channel.unary_unary(
                '/com.atakmap.FederatedChannel/SendOneBlob',
                request_serializer=fig__pb2.BinaryBlob.SerializeToString,
                response_deserializer=fig__pb2.Empty.FromString,
                _registered_method=True)
        self.getIdentity = channel.unary_unary(
                '/com.atakmap.FederatedChannel/getIdentity',
                request_serializer=fig__pb2.Empty.SerializeToString,
                response_deserializer=fig__pb2.Identity.FromString,
                _registered_method=True)
        self.ClientEventStream = channel.unary_stream(
                '/com.atakmap.FederatedChannel/ClientEventStream',
                request_serializer=fig__pb2.Subscription.SerializeToString,
                response_deserializer=fig__pb2.FederatedEvent.FromString,
                _registered_method=True)
        self.ServerEventStream = channel.stream_unary(
                '/com.atakmap.FederatedChannel/ServerEventStream',
                request_serializer=fig__pb2.FederatedEvent.SerializeToString,
                response_deserializer=fig__pb2.Subscription.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/com.atakmap.FederatedChannel/HealthCheck',
                request_serializer=fig__pb2.ClientHealth.SerializeToString,
                response_deserializer=fig__pb2.ServerHealth.FromString,
                _registered_method=True)
        self.ClientROLStream = channel.unary_stream(
                '/com.atakmap.FederatedChannel/ClientROLStream',
                request_serializer=fig__pb2.Subscription.SerializeToString,
                response_deserializer=fig__pb2.ROL.FromString,
                _registered_method=True)
        self.ServerROLStream = channel.stream_unary(
                '/com.atakmap.FederatedChannel/ServerROLStream',
                request_serializer=fig__pb2.ROL.SerializeToString,
                response_deserializer=fig__pb2.Subscription.FromString,
                _registered_method=True)
        self.ServerFederateGroupsStream = channel.unary_stream(
                '/com.atakmap.FederatedChannel/ServerFederateGroupsStream',
                request_serializer=fig__pb2.Subscription.SerializeToString,
                response_deserializer=fig__pb2.FederateGroups.FromString,
                _registered_method=True)
        self.ClientFederateGroupsStream = channel.stream_unary(
                '/com.atakmap.FederatedChannel/ClientFederateGroupsStream',
                request_serializer=fig__pb2.FederateGroups.SerializeToString,
                response_deserializer=fig__pb2.Subscription.FromString,
                _registered_method=True)
        self.GetAuthTokenByX509 = channel.unary_unary(
                '/com.atakmap.FederatedChannel/GetAuthTokenByX509',
                request_serializer=fig__pb2.BinaryBlob.SerializeToString,
                response_deserializer=fig__pb2.FederateTokenResponse.FromString,
                _registered_method=True)
        self.Getx509Identity = channel.unary_unary(
                '/com.atakmap.FederatedChannel/Getx509Identity',
                request_serializer=fig__pb2.Empty.SerializeToString,
                response_deserializer=fig__pb2.BinaryBlob.FromString,
                _registered_method=True)


class FederatedChannelServicer(object):
    """Federation v2 transport. v1 exchanges FederatedEvent as length-prefixed
    frames over a raw TLS socket and ignores this service; v2 uses these RPCs
    over gRPC/HTTP2. OpenTAKServer implements the situational-awareness subset:
    getIdentity, HealthCheck, and the ClientEventStream/ServerEventStream event
    streams. The ROL (mission federation) and group-mapping RPCs are declared
    for wire compatibility but not served.
    """

    def SendOneEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BinaryMessageStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendOneBlob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def getIdentity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClientEventStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ServerEventStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClientROLStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ServerROLStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ServerFederateGroupsStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClientFederateGroupsStream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAuthTokenByX509(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Getx509Identity(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FederatedChannelServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendOneEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.SendOneEvent,
                    request_deserializer=fig__pb2.FederatedEvent.FromString,
                    response_serializer=fig__pb2.Empty.SerializeToString,
            ),
            'BinaryMessageStream': grpc.stream_unary_rpc_method_handler(
                    servicer.BinaryMessageStream,
                    request_deserializer=fig__pb2.BinaryBlob.FromString,
                    response_serializer=fig__pb2.Empty.SerializeToString,
            ),
            'SendOneBlob': grpc.unary_unary_rpc_method_handler(
                    servicer.SendOneBlob,
                    request_deserializer=fig__pb2.BinaryBlob.FromString,
                    response_serializer=fig__pb2.Empty.SerializeToString,
            ),
            'getIdentity': grpc.unary_unary_rpc_method_handler(
                    servicer.getIdentity,
                    request_deserializer=fig__pb2.Empty.FromString,
                    response_serializer=fig__pb2.Identity.SerializeToString,
            ),
            'ClientEventStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ClientEventStream,
                    request_deserializer=fig__pb2.Subscription.FromString,
                    response_serializer=fig__pb2.FederatedEvent.SerializeToString,
            ),
            'ServerEventStream': grpc.stream_unary_rpc_method_handler(
                    servicer.ServerEventStream,
                    request_deserializer=fig__pb2.FederatedEvent.FromString,
                    response_serializer=fig__pb2.Subscription.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=fig__pb2.ClientHealth.FromString,
                    response_serializer=fig__pb2.ServerHealth.SerializeToString,
            ),
            'ClientROLStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ClientROLStream,
                    request_deserializer=fig__pb2.Subscription.FromString,
                    response_serializer=fig__pb2.ROL.SerializeToString,
            ),
            'ServerROLStream': grpc.stream_unary_rpc_method_handler(
                    servicer.ServerROLStream,
                    request_deserializer=fig__pb2.ROL.FromString,
                    response_serializer=fig__pb2.Subscription.SerializeToString,
            ),
            'ServerFederateGroupsStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ServerFederateGroupsStream,
                    request_deserializer=fig__pb2.Subscription.FromString,
                    response_serializer=fig__pb2.FederateGroups.SerializeToString,
            ),
            'ClientFederateGroupsStream': grpc.stream_unary_rpc_method_handler(
                    servicer.ClientFederateGroupsStream,
                    request_deserializer=fig__pb2.FederateGroups.FromString,
                    response_serializer=fig__pb2.Subscription.SerializeToString,
            ),
            'GetAuthTokenByX509': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAuthTokenByX509,
                    request_deserializer=fig__pb2.BinaryBlob.FromString,
                    response_serializer=fig__pb2.FederateTokenResponse.SerializeToString,
            ),
            'Getx509Identity': grpc.unary_unary_rpc_method_handler(
                    servicer.Getx509Identity,
                    request_deserializer=fig__pb2.Empty.FromString,
                    response_serializer=fig__pb2.BinaryBlob.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.atakmap.FederatedChannel', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('com.atakmap.FederatedChannel', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FederatedChannel(object):
    """Federation v2 transport. v1 exchanges FederatedEvent as length-prefixed
    frames over a raw TLS socket and ignores this service; v2 uses these RPCs
    over gRPC/HTTP2. OpenTAKServer implements the situational-awareness subset:
    getIdentity, HealthCheck, and the ClientEventStream/ServerEventStream event
    streams. The ROL (mission federation) and group-mapping RPCs are declared
    for wire compatibility but not served.
    """

    @staticmethod
    def SendOneEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.atakmap.FederatedChannel/SendOneEvent',
            fig__pb2.FederatedEvent.SerializeToString,
            fig__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BinaryMessageStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/com.atakmap.FederatedChannel/BinaryMessageStream',
            fig__pb2.BinaryBlob.SerializeToString,
            fig__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendOneBlob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.atakmap.FederatedChannel/SendOneBlob',
            fig__pb2.BinaryBlob.SerializeToString,
            fig__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def getIdentity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.atakmap.FederatedChannel/getIdentity',
            fig__pb2.Empty.SerializeToString,
            fig__pb2.Identity.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClientEventStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/com.atakmap.FederatedChannel/ClientEventStream',
            fig__pb2.Subscription.SerializeToString,
            fig__pb2.FederatedEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ServerEventStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/com.atakmap.FederatedChannel/ServerEventStream',
            fig__pb2.FederatedEvent.SerializeToString,
            fig__pb2.Subscription.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.atakmap.FederatedChannel/HealthCheck',
            fig__pb2.ClientHealth.SerializeToString,
            fig__pb2.ServerHealth.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClientROLStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/com.atakmap.FederatedChannel/ClientROLStream',
            fig__pb2.Subscription.SerializeToString,
            fig__pb2.ROL.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ServerROLStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/com.atakmap.FederatedChannel/ServerROLStream',
            fig__pb2.ROL.SerializeToString,
            fig__pb2.Subscription.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ServerFederateGroupsStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/com.atakmap.FederatedChannel/ServerFederateGroupsStream',
            fig__pb2.Subscription.SerializeToString,
            fig__pb2.FederateGroups.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClientFederateGroupsStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/com.atakmap.FederatedChannel/ClientFederateGroupsStream',
            fig__pb2.FederateGroups.SerializeToString,
            fig__pb2.Subscription.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAuthTokenByX509(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.atakmap.FederatedChannel/GetAuthTokenByX509',
            fig__pb2.BinaryBlob.SerializeToString,
            fig__pb2.FederateTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Getx509Identity(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.atakmap.FederatedChannel/Getx509Identity',
            fig__pb2.Empty.SerializeToString,
            fig__pb2.BinaryBlob.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
