"""Added mission guid to MissionRole and MissionInvitaion

Revision ID: 00442761c803
Revises: 6a7929c07690
Create Date: 2026-03-28 19:06:27.954358

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '00442761c803'
down_revision = '6a7929c07690'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mission_invitations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mission_guid', sa.String(length=255), nullable=True))

    with op.batch_alter_table('mission_roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mission_guid', sa.String(length=255), nullable=True))
        batch_op.alter_column('mission_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mission_roles', schema=None) as batch_op:
        batch_op.alter_column('mission_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('mission_guid')

    with op.batch_alter_table('mission_invitations', schema=None) as batch_op:
        batch_op.drop_column('mission_guid')

    # ### end Alembic commands ###
