"""Added citrap table

Revision ID: 1a62289c9301
Revises: 640de7aafac2
Create Date: 2026-08-21 23:14:13.740447

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "1a62289c9301"
down_revision = "640de7aafac2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "citrap",
        sa.Column("id", sa.String(length=255), nullable=False, primary_key=True),
        sa.Column("type", sa.String(length=255), nullable=True),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("visible", sa.Boolean(), nullable=True),
        sa.Column("delimiter", sa.String(length=255), nullable=True),
        sa.Column("user_callsign", sa.String(length=255), nullable=True),
        sa.Column("user_description", sa.String(length=255), nullable=True),
        sa.Column("date_time", sa.DateTime(), nullable=True),
        sa.Column("date_time_description", sa.String(length=255), nullable=True),
        sa.Column("point_id", sa.Integer(), nullable=False),
        sa.Column("location_description", sa.String(length=255), nullable=True),
        sa.Column("event_scale", sa.String(length=255), nullable=True),
        sa.Column("importance", sa.String(length=255), nullable=True),
        sa.Column("tags", sa.String(length=255), nullable=False),
        sa.Column("scale_description", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=255), nullable=False),
        sa.Column("file_name", sa.String(length=255), nullable=False),
        sa.Column("hash", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(["point_id"], ["points.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table("citrap")
    # ### end Alembic commands ###
