"""Added id column to device_profiles

Revision ID: 591a98184047
Revises: 61c7cfea0c86
Create Date: 2026-01-30 03:54:18.307669

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "591a98184047"
down_revision = "61c7cfea0c86"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("device_profiles", schema=None) as batch_op:
        batch_op.drop_constraint("preference_key", type_="primary")
        batch_op.create_primary_key("primary_key", ["preference_key", "eud_uid"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("device_profiles", schema=None) as batch_op:
        batch_op.drop_constraint("primary_key", type_="primary")
        batch_op.create_primary_key("preference_key", ["preference_key"])

    # ### end Alembic commands ###
