"""Added GeoAlchemy2 support to points table

Revision ID: 640de7aafac2
Revises: 00442761c803
Create Date: 2026-08-21 13:12:18.083709

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import Session
import geoalchemy2

from opentakserver.models.Point import Point

# revision identifiers, used by Alembic.
revision = '640de7aafac2'
down_revision = '00442761c803'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('points', schema=None) as batch_op:
        batch_op.add_column(sa.Column('point', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=3, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))

    session = Session(bind=op.get_bind())
    points = session.query(Point).all()

    commit = 0
    for point in points:
        latitude = point.latitude if point.latitude is not None else 0
        longitude = point.longitude if point.longitude is not None else 0
        point.point = f"POINT({longitude} {latitude})"
        session.add(point)
        # Run commit after every 100 points to avoid problems with tables with lots of rows
        if commit >= 100:
            session.commit()
            commit = 0
        commit += 1
    # Commit the last couple of rows
    session.commit()

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('points', schema=None) as batch_op:
        batch_op.drop_column('point')

    # ### end Alembic commands ###
