"""Update for groups support

Revision ID: 654486d08787
Revises: d68964dab66b
Create Date: 2025-09-12 17:52:10.965451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '654486d08787'
down_revision = 'd68964dab66b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups_users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    op.drop_table('groups_euds')

    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('distinguishedName', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('direction', sa.Enum('IN', 'OUT', name='groupdirectionenum'), nullable=False))
        batch_op.add_column(sa.Column('type', sa.Enum('SYSTEM', 'LDAP', name='grouptypeenum'), nullable=False))
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=False))
        batch_op.drop_column('group_name')
        batch_op.drop_column('group_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_type', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('group_name', sa.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('active')
        batch_op.drop_column('description')
        batch_op.drop_column('type')
        batch_op.drop_column('direction')
        batch_op.drop_column('distinguishedName')
        batch_op.drop_column('name')

    op.create_table('groups_euds',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('group_id', sa.INTEGER(), nullable=False),
    sa.Column('direction', sa.VARCHAR(length=255), nullable=False),
    sa.Column('active', sa.BOOLEAN(), nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), nullable=True),
    sa.Column('eud_uid', sa.VARCHAR(length=255), nullable=False),
    sa.ForeignKeyConstraint(['eud_uid'], ['euds.uid'], name=op.f('group_eud'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('groups_users')
    # ### end Alembic commands ###
