"""Added device profile table

Revision ID: 673883afccae
Revises: 04d5dc15acab
Create Date: 2024-09-05 02:02:04.982327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '673883afccae'
down_revision = '04d5dc15acab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('profile_type', sa.String(), nullable=False),
    sa.Column('tool', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('device_profiles_data_packages',
    sa.Column('device_profile_id', sa.Integer(), nullable=False),
    sa.Column('data_package_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['data_package_id'], ['data_packages.id'], ),
    sa.ForeignKeyConstraint(['device_profile_id'], ['device_profiles.id'], ),
    sa.PrimaryKeyConstraint('device_profile_id', 'data_package_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device_profiles_data_packages')
    op.drop_table('device_profiles')
    # ### end Alembic commands ###
