"""altered foreign key on device_profiles

Revision ID: 6a7929c07690
Revises: 591a98184047
Create Date: 2026-02-20 23:36:36.134346

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "6a7929c07690"
down_revision = "591a98184047"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("device_profiles", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("eud_uid"), type_="foreignkey")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("device_profiles", schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f("eud_uid"), "euds", ["eud_uid"], ["uid"])

    # ### end Alembic commands ###
