"""Added federation_groups table

Revision ID: 8bc1fb003330
Revises: 9b37b021e2e5
Create Date: 2026-09-25 19:05:47.084265

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "8bc1fb003330"
down_revision = "9b37b021e2e5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "federation_groups",
        sa.Column("federation_id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("direction", sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(
            ["federation_id"],
            ["federation_connections.id"],
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.PrimaryKeyConstraint("federation_id", "group_id", "direction"),
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("federation_groups")
    # ### end Alembic commands ###
