"""Added federation table

Revision ID: 9b37b021e2e5
Revises: 9e8eaa6c5a4d
Create Date: 2026-09-02 12:10:35.506748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b37b021e2e5'
down_revision = '9e8eaa6c5a4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('federate_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('expiration', sa.DateTime(), nullable=False),
    sa.Column('token', sa.String(length=1024), nullable=False),
    sa.Column('share_alerts', sa.Boolean(), nullable=False),
    sa.Column('archive', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('federates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('shared_alerts', sa.Boolean(), nullable=False),
    sa.Column('archive', sa.Boolean(), nullable=False),
    sa.Column('federate_group_matching', sa.Boolean(), nullable=False),
    sa.Column('automatic_group_matching', sa.Boolean(), nullable=False),
    sa.Column('fallback_group_matching', sa.Boolean(), nullable=False),
    sa.Column('max_hops', sa.Integer(), nullable=False),
    sa.Column('use_group_hop_limiting', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('certificate_file', sa.String(length=255), nullable=False),
    sa.Column('issuer', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('serial_number', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serial_number')
    )
    op.create_table('federation_connections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('protocol_version', sa.String(length=255), nullable=False),
    sa.Column('reconnect_interval', sa.Integer(), nullable=False),
    sa.Column('unlimited_retries', sa.Boolean(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('federate_id', sa.Integer(), nullable=True),
    sa.Column('fallback_connection', sa.Integer(), nullable=True),
    sa.Column('use_token_auth', sa.Boolean(), nullable=False),
    sa.Column('auth_token_type', sa.Enum('AUTOMATIC', 'MANUAL', name='authtokentypeenum'), nullable=True),
    sa.Column('auth_token', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.String(length=1024), nullable=True),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('uid', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['auth_token'], ['federate_tokens.id'], ),
    sa.ForeignKeyConstraint(['fallback_connection'], ['federation_connections.id'], ),
    sa.ForeignKeyConstraint(['federate_id'], ['federates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table('federation_connections')
    op.drop_table('federates')
    op.drop_table('federate_tokens')
    # ### end Alembic commands ###
