"""Added groups_citrap table

Revision ID: 9e8eaa6c5a4d
Revises: 1a62289c9301
Create Date: 2026-09-02 02:46:44.859540

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "9e8eaa6c5a4d"
down_revision = "1a62289c9301"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "groups_citrap",
        sa.Column("citrap_id", sa.String(length=255), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["citrap_id"],
            ["citrap.id"],
        ),
        sa.ForeignKeyConstraint(
            ["group_id"],
            ["groups.id"],
        ),
        sa.PrimaryKeyConstraint("citrap_id", "group_id"),
    )

    with op.batch_alter_table("citrap", schema=None) as batch_op:
        batch_op.alter_column("tags", existing_type=sa.VARCHAR(length=255), nullable=True)
        batch_op.alter_column(
            "scale_description", existing_type=sa.VARCHAR(length=255), nullable=True
        )
        batch_op.alter_column("status", existing_type=sa.VARCHAR(length=255), nullable=True)
        batch_op.alter_column("file_name", existing_type=sa.VARCHAR(length=255), nullable=True)
        batch_op.alter_column("hash", existing_type=sa.VARCHAR(length=255), nullable=True)
        batch_op.create_unique_constraint("citrap_hash_constraint", ["hash"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("citrap", schema=None) as batch_op:
        batch_op.drop_constraint("citrap_hash_constraint", type_="unique")
        batch_op.alter_column("hash", existing_type=sa.VARCHAR(length=255), nullable=False)
        batch_op.alter_column("file_name", existing_type=sa.VARCHAR(length=255), nullable=False)
        batch_op.alter_column("status", existing_type=sa.VARCHAR(length=255), nullable=False)
        batch_op.alter_column(
            "scale_description", existing_type=sa.VARCHAR(length=255), nullable=False
        )
        batch_op.alter_column("tags", existing_type=sa.VARCHAR(length=255), nullable=False)

    with op.batch_alter_table("apscheduler_jobs", schema=None) as batch_op:
        batch_op.alter_column(
            "id",
            existing_type=sa.String(length=255),
            type_=sa.VARCHAR(length=191),
            existing_nullable=False,
        )

    op.drop_table("groups_citrap")
    # ### end Alembic commands ###
