"""Added federation tables

Revision ID: a1b2c3d4e5f6
Revises: f6dfc571d31c
Create Date: 2025-10-28 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = 'f6dfc571d31c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('federation_servers',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('node_id', sa.String(length=255), nullable=True),
        sa.Column('address', sa.String(length=255), nullable=False),
        sa.Column('port', sa.Integer(), nullable=False),
        sa.Column('connection_type', sa.String(length=50), nullable=False),
        sa.Column('protocol_version', sa.String(length=10), nullable=False),
        sa.Column('use_tls', sa.Boolean(), nullable=False),
        sa.Column('ca_certificate', sa.Text(), nullable=True),
        sa.Column('client_certificate', sa.Text(), nullable=True),
        sa.Column('client_key', sa.Text(), nullable=True),
        sa.Column('verify_ssl', sa.Boolean(), nullable=False),
        sa.Column('enabled', sa.Boolean(), nullable=False),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('last_connected', sa.DateTime(), nullable=True),
        sa.Column('last_error', sa.Text(), nullable=True),
        sa.Column('sync_missions', sa.Boolean(), nullable=False),
        sa.Column('sync_cot', sa.Boolean(), nullable=False),
        sa.Column('mission_filter', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )

    op.create_table('federation_outbound',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('federation_server_id', sa.Integer(), nullable=False),
        sa.Column('mission_change_id', sa.Integer(), nullable=False),
        sa.Column('sent', sa.Boolean(), nullable=False),
        sa.Column('sent_at', sa.DateTime(), nullable=True),
        sa.Column('acknowledged', sa.Boolean(), nullable=False),
        sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
        sa.Column('retry_count', sa.Integer(), nullable=False),
        sa.Column('last_retry_at', sa.DateTime(), nullable=True),
        sa.Column('last_error', sa.String(length=1000), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['federation_server_id'], ['federation_servers.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['mission_change_id'], ['mission_changes.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )

    # Create indexes for better query performance
    op.create_index('ix_federation_outbound_server_sent', 'federation_outbound',
                    ['federation_server_id', 'sent'])
    op.create_index('ix_federation_outbound_mission_change', 'federation_outbound',
                    ['mission_change_id'])
    op.create_index('ix_federation_servers_enabled', 'federation_servers',
                    ['enabled'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_federation_servers_enabled', table_name='federation_servers')
    op.drop_index('ix_federation_outbound_mission_change', table_name='federation_outbound')
    op.drop_index('ix_federation_outbound_server_sent', table_name='federation_outbound')
    op.drop_table('federation_outbound')
    op.drop_table('federation_servers')
    # ### end Alembic commands ###
