"""Mission table

Revision ID: b99dcc9500af
Revises: d91957bb59a0
Create Date: 2024-07-24 19:47:59.863287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b99dcc9500af'
down_revision = 'd91957bb59a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('missions',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('chatRoom', sa.String(), nullable=True),
    sa.Column('baseLayer', sa.String(), nullable=True),
    sa.Column('bbox', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('classification', sa.String(), nullable=True),
    sa.Column('tool', sa.String(), nullable=True),
    sa.Column('group', sa.String(), nullable=True),
    sa.Column('defaultRole', sa.String(), nullable=True),
    sa.Column('permissions', sa.String(), nullable=True),
    sa.Column('keywords', sa.String(), nullable=True),
    sa.Column('creatorUid', sa.String(), nullable=True),
    sa.Column('creationTime', sa.Integer(), nullable=True),
    sa.Column('externalData', sa.String(), nullable=True),
    sa.Column('feeds', sa.String(), nullable=True),
    sa.Column('mapLayers', sa.String(), nullable=True),
    sa.Column('inviteOnly', sa.Boolean(), nullable=False),
    sa.Column('expiration', sa.Integer(), nullable=False),
    sa.Column('guid', sa.String(), nullable=True),
    sa.Column('uids', sa.String(), nullable=True),
    sa.Column('contents', sa.String(), nullable=True),
    sa.Column('passwordProtected', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('missions')
    # ### end Alembic commands ###
