"""More data sync

Revision ID: badc8108eab0
Revises: f6dfc571d31c
Create Date: 2024-10-25 04:05:54.849299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'badc8108eab0'
down_revision = 'f6dfc571d31c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mission_invitations', schema=None) as batch_op:
        batch_op.create_foreign_key('euds', 'euds', ['client_uid'], ['uid'])

    with op.batch_alter_table('missions', schema=None) as batch_op:
        batch_op.create_foreign_key('euds', 'euds', ['creator_uid'], ['uid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('missions', schema=None) as batch_op:
        batch_op.drop_constraint('euds', type_='foreignkey')

    with op.batch_alter_table('mission_invitations', schema=None) as batch_op:
        batch_op.drop_constraint('euds', type_='foreignkey')

    # ### end Alembic commands ###
