"""More data sync stuff

Revision ID: d1f5df78eace
Revises: 4f0173cdb93b
Create Date: 2024-10-15 03:02:43.059600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1f5df78eace'
down_revision = '4f0173cdb93b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mission_changes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_uid', sa.String(), nullable=True))
        batch_op.create_foreign_key("mission_content", 'mission_content', ['content_uid'], ['uid'])

    with op.batch_alter_table('mission_content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.String(), nullable=True))
        batch_op.drop_column('name')

    with op.batch_alter_table('mission_invitations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('callsign', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('username', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('group_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('team_name', sa.String(), nullable=True))
        batch_op.alter_column('client_uid',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.create_foreign_key('user', 'user', ['username'], ['username'])
        batch_op.create_foreign_key('groups', 'groups', ['group_name'], ['group_name'])
        batch_op.create_foreign_key('euds', 'euds', ['callsign'], ['callsign'])
        batch_op.create_foreign_key('teams', 'teams', ['team_name'], ['name'])
        batch_op.create_foreign_key('euds', 'euds', ['client_uid'], ['uid'])

    with op.batch_alter_table('missions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group', sa.String(), nullable=True))
        batch_op.alter_column('create_time',
               existing_type=sa.INTEGER(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.create_foreign_key('groups', 'groups', ['group'], ['group_name'])
        batch_op.drop_column('group_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('missions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_name', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('create_time',
               existing_type=sa.DateTime(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.drop_column('group')

    with op.batch_alter_table('mission_invitations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('client_uid',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('team_name')
        batch_op.drop_column('group_name')
        batch_op.drop_column('username')
        batch_op.drop_column('callsign')

    with op.batch_alter_table('mission_content', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('filename')

    with op.batch_alter_table('mission_changes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('content_uid')

    op.create_table('apscheduler_jobs',
    sa.Column('id', sa.VARCHAR(length=191), nullable=False),
    sa.Column('next_run_time', sa.FLOAT(), nullable=True),
    sa.Column('job_state', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('apscheduler_jobs', schema=None) as batch_op:
        batch_op.create_index('ix_apscheduler_jobs_next_run_time', ['next_run_time'], unique=False)

    # ### end Alembic commands ###
