"""Added groups table

Revision ID: d4cc3d4afdb9
Revises: d1f5df78eace
Create Date: 2024-10-15 19:03:59.996651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4cc3d4afdb9'
down_revision = 'd1f5df78eace'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('group_type', sa.String(), nullable=False),
    sa.Column('bitpos', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    with op.batch_alter_table('mission_invitations', schema=None) as batch_op:
        batch_op.create_foreign_key('groups', 'groups', ['group_name'], ['group_name'])
        batch_op.create_foreign_key('euds', 'euds', ['callsign'], ['callsign'])

    with op.batch_alter_table('missions', schema=None) as batch_op:
        batch_op.create_foreign_key('groups', 'groups', ['group'], ['group_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('missions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('mission_invitations', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('groups')
    # ### end Alembic commands ###
